sudo: false
language: cpp
compiler:
  - clang
  - gcc

before_install:
 - sudo add-apt-repository --yes ppa:ubuntu-sdk-team/ppa
 - sudo apt-get update -qq
 - sudo apt-get install qtbase5-dev qtdeclarative5-dev libqt5webkit5-dev libsqlite3-dev
 - sudo apt-get install qt5-default qttools5-dev-tools
 - sudo apt-get install libcppunit-dev

addons:
  coverity_scan:
    project:
      name: "bschramke/oauth2cpp"
      description: "Build submitted via Travis CI"
    notification_email: bjoern@schramke-online.de
    build_command_prepend: "make clean"
    build_command:   "make"
    branch_pattern: develop

script:
  - mkdir _build && cd _build 
  - qmake ../oauth2cpp.pro
  - make
