language: cpp
sudo: false

# from http://stackoverflow.com/a/32127147/266378
matrix:
  include:
    - os: linux
      compiler: gcc
      addons:
        apt:
          sources: ['ubuntu-toolchain-r-test', 'ubuntu-sdk-team-ppa']
          packages: ['g++-4.9', 'valgrind']
      env: COMPILER=g++-4.9

    - os: linux
      compiler: gcc
      addons:
        apt:
          sources: ['ubuntu-toolchain-r-test', 'ubuntu-sdk-team-ppa']
          packages: ['g++-5', 'valgrind']
      env: COMPILER=g++-5

    - os: linux
      compiler: clang
      addons:
        apt:
          sources: ['ubuntu-toolchain-r-test', 'llvm-toolchain-precise-3.6', 'ubuntu-sdk-team-ppa']
          packages: ['clang-3.6', 'valgrind']
      env: COMPILER=clang++-3.6

addons:
  apt:
    sources:
      - ubuntu-sdk-team-ppa
      - boost-latest
    packages:
      - libcppunit-dev
      - libboost1.55-all-dev
      - qt5-default
      - qtbase5-dev
      - qttools5-dev-tools
      - qtdeclarative5-dev
      - libqt5webkit5-dev
      - libsqlite3-dev
      
  coverity_scan:
    project:
      name: "bschramke/oauth2cpp"
      description: "Build submitted via Travis CI"
    notification_email: bjoern@schramke-online.de
    build_command_prepend: "make clean"
    build_command:   "make"
    branch_pattern: develop

script:
  - mkdir _build && cd _build 
  - qmake ../oauth2cpp.pro
  - make
